# Generated by Django 4.0.2 on 2022-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='sandip', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
