# Generated by Django 4.0.2 on 2022-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_userprofile_about_me_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='why_hire_me',
            field=models.CharField(default="I'm the best developer in the marketplace", max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='my_positions',
            field=models.TextField(default='Developer\r\nHacker\r\nUI/UX Designer'),
        ),
    ]
