# Generated by Django 4.0.2 on 2022-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_rename_display_testimonial_userprofile_display_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gmap_iframe',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
