# Generated by Django 4.0.2 on 2022-03-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_education_date_to_alter_experiences_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
