# Generated by Django 4.0.2 on 2022-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_education_date_to_alter_experiences_date_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-date_from',)},
        ),
        migrations.AlterModelOptions(
            name='experiences',
            options={'ordering': ('-date_from',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
