# Generated by Django 4.0.2 on 2022-03-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='resume.userprofile'),
        ),
    ]
