# Generated by Django 4.0.2 on 2022-03-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_requestedappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('-created_at',)},
        ),
    ]
