# Generated by Django 4.0.2 on 2022-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_blog_options_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='pinterest',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
